### PR TITLE
Fix/check transaction details

### PR DESCRIPTION
**Pull request by rosseti**
I changed transaction check to use by default the payload from XUMM platform.

### CODE REVIEW

**Comment by WietseWind** [comment]
@rosseti @KoenPaas It is highly advisable to use an actual mainnet cluster for transaction verification, as that's a more neutral source of truth than the Xumm platform. Who knows, we may be off on a fork, while the XRPL mainnet spins on.

Hence, relying (just like how testnet is implemented now) on a query to a public cluster like `xrplcluster.com` is preferred over fetching the transaction outcome through the Xumm APIs.

**Comment by rosseti** [comment]
@WietseWind @KoenPaas Yesterday, I changed the codebase used on MainnetTransactionRequest to use official xumm api request, and for Testnet I am using https://s.altnet.rippletest.net:51234 via json-rpc.

**Comment by WietseWind** [comment]
> @WietseWind @KoenPaas Yesterday, I changed the codebase used on MainnetTransactionRequest to use official xumm api request, and for Testnet I am using https://s.altnet.rippletest.net:51234 via json-rpc.

I realized (and I appreciate your work! Sincerely!) 

But the fact that I noticed the commit switch from MainnetTransactionRequest to Xumm API for mainnet tx verification was the reason for me to comment that actually the MainnetTransactionRequest solution was better ;)

> It is highly advisable to use an actual mainnet cluster for transaction verification, as that's a more neutral source of truth than the Xumm platform. Who knows, we may be off on a fork, while the XRPL mainnet spins on.

> Hence, relying (just like how testnet is implemented now) on a query to a public cluster like xrplcluster.com is preferred over fetching the transaction outcome through the Xumm APIs.

**Comment by rosseti** [comment]
Thank you so Much @WietseWind

**Pull request merged**
